### ISSUE TITLE
Action group to activate relay

### ISSUE THREAD

**Issue by durosity** [papamac/VirtualGarageDoor#1]
Hey, I might've asked this before but I can't find it so apologies if this is a duplicate.

Would it be possible to add action groups to the relay device?  The relay I use is connected using my DSC Alarm Panel and doesn't have a device (I currently have it set up as a virtual switch, but it's clunky and needs variables and triggers and action groups to work properly).  I'd love to be able to have this plugin run the action group, but as it stands at the moment it only lists devices in the list.  Even if I could specify the action group ID number that'd help massively 🙂.

**Comment by papamac** [comment]
Hi Mike,

The VGD plugin cannot use an action group as the activation relay (ar) device because the ar device is used as an activation sensor as well.  The Indigo deviceUpdated method is used to detect a state change in the ar device, so it must be a normal Indigo device with an onOffState.

I do, however, have a suggestion. Define an Indigo virtual on/off device as your activation relay.  This device requires one action group for turnOn of the virtual device and one action group for turnOff.  These action groups can control your DSC relay.  The virtual on/off device has a deviceTypeId of “pseudoRelay”, and will be recognized by the VGD plugin when you select your activation relay.

In the future please address these issues on the Indigo forums.  A similar issue was already addressed on https://forums.indigodomo.com/viewtopic.php?f=374&t=26514. 

Let me know if this works for you.  Good luck!

papamac

**Comment by durosity** [comment]
Ah that was the request I thought I made but couldn't find! 😂

**Comment by papamac** [comment]
Let me know if I can help.

papamac
